name: Deploy documentation to Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/formalsec/ocaml-4.14-z3:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Install Dependencies
        run: |
          opam install -y . --deps-only --with-doc --with-test
          opam install bisect_ppx

      - name: Build doc
        run: opam exec -- dune build @doc

      - name: Coverage report
        run: |
          BISECT_FILE=`pwd`/bisect dune runtest --force --instrument-with bisect_ppx || true
          bisect-ppx-report html -o _build/default/_doc/_html/coverage
          bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload entire repository
          path: '_build/default/_doc/_html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
