name: Test Colibri2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-colibri2:
    runs-on: ubuntu-latest
    env:
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/_opam
          key: ${{ runner.os }}-test-colibri2-4.14-${{ hashFiles('**.opam') }}
          restore-keys: |
            ${{ runner.os }}-opam-4.14-

      - name: Setup OCaml 4.14
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14"
          dune-cache: true
          allow-prerelease-opam: true

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: opam install -y . --deps-only --with-test

      - name: Install Colibri2
        if: steps.cache.outputs.cache-hit != 'true'
        run: opam upgrade colibri2

      - name: Build
        run: opam exec -- dune build @install

      - name: Test
        run: opam exec -- dune exec ./test/test_colibri2.exe
