name: Test Alt-Ergo

on: workflow-dispatch

jobs:
  test-alt-ergo:
    runs-on: ubuntu-latest
    env:
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OCaml 4.14
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "4.14"
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install -y . --deps-only --with-test
          opam install alt-ergo-lib

      - name: Build
        run: opam exec -- dune build @install

      - name: Test
        run: opam exec -- dune runtest
