name: Test Alt-Ergo

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  test-alt-ergo:
    runs-on: ubuntu-latest
    env:
      OPAMCONFIRMLEVEL: unsafe-yes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Removes ·git to prevent opam from checking out submodueles
      - name: Remove .git
        run: rm -rf .git

      - name: Setup OCaml 5.3
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.3"
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install -y . --deps-only --with-test
          opam install alt-ergo-lib

      - name: Build
        run: opam exec -- dune build @install

      - name: Test
        run: opam exec -- dune runtest
